build:
  environment:
    python: "pypy3.10-9.0.0"  # Use PyPy 3.10 
  dependencies:
    before:
      -  g++  Rohan.c -o Rohan  -pthread 
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - python3 -m pip install --upgrade pip
      - pip install telebot 
  tests:
    override:
      - chmod +x  Rohan || true  # Prevent failure if file doesn't exist
      - python3  Rohan.py
